// Package incoming provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package incoming

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Description *string            `json:"description,omitempty"`
	TaskId      openapi_types.UUID `json:"task_id"`
	Title       string             `json:"title"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse = []TaskResponse

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = TaskRequest

// PutTaskJSONRequestBody defines body for PutTask for application/json ContentType.
type PutTaskJSONRequestBody = TaskRequest
